import type { Project } from './projects.types';

export const PROJECTS: readonly Project[] = [
  {
    id: 'bulkyhub',
    title: 'BulkyHub — Bulky Waste Pickup Platform',
    description: 'A scheduling and tracking platform for bulky waste pickup: residents submit requests, pick slots by RW capacity, and track status using a booking code.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'Framer Motion', 'Rest API'],
    highlights: [
      'Implemented a multi-step pickup request flow including user and location details, item selection, and verification summary.',
      'Slot-based scheduling per RW capacity + admin slot management',
      'Tracking page using booking code with status progression',
    ],
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-landingpage.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-form.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-formdetail.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-verif.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-uploadproof.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-track.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-loginadmin.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-dashboard.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-pickuprequest.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-schedule.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-assignment.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-detailassignment.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-truckmanagement.png` },
    ],

    image: `${import.meta.env.BASE_URL}projects/bulkyhub.png`,
    links: {
      github: 'https://github.com/wildanzhafiri/BulkyHub-FE',
    },
  },
  {
    id: 'laporin',
    title: 'LaporIn — Public Complaint Reporting System',
    description: 'A smart-city reporting web app where citizens submit complaints with a ticket number and track status, while admins verify and resolve reports.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'Rest API'],
    highlights: [
      'Developed a smart-city complaint reporting web app with ticket-based tracking and admin resolution flow.',
      'Built complaint submission form with validation and photo upload',
      'Implemented report history with list and detail views, along with status tracking including New, In Review, Rejected, and Resolved.',
      'Created admin dashboard to verify reports and update status with confirmation.',
    ],
    image: `${import.meta.env.BASE_URL}projects/laporin.png`,
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin1.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin2.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin3.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin4.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin5.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin6.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin7.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin8.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin9.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin10.png` },
    ],
    links: {
      live: 'http://laporin.bccdev.id/admin',
      github: 'https://github.com/wildanzhafiri/fe-LaporIn',
    },
  },
  {
    id: 'emub2025',
    title: 'EM UB 2025 Website',
    description: 'A profile website for Eksekutif Mahasiswa Universitas Brawijaya 2025 featuring programs, organizational structure, about section, magazine content, and a new work program registration feature.',
    role: 'Front-end Developer',
    tags: ['Next.js', 'TypeScript', 'Tailwind', 'GraphQL', 'Framer Motion'],
    highlights: [
      'Implemented the landing page and core navigation flow of the EM UB 2025 website',
      'Built detailed work program pages and implemented an announcement feature',
      'Developed a work program registration form with various input types and auto save functionality',
      'Integrated Google authentication for user login and GraphQL for data handling across the site',
    ],

    image: `${import.meta.env.BASE_URL}projects/em2.png`,
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/em/em1.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em2.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em3.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em4.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em5.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em6.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em7.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em8.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em9.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em10.png` },
      { src: `${import.meta.env.BASE_URL}projects/em/em11.png` },
    ],
    links: {
      live: 'https://em.ub.ac.id/',
      // github: 'https://github.com/...',
    },
  },
  {
    id: 'kenalbatik',
    title: 'Kenal Batik — Cultural Education & Interactive Learning',
    description: 'An educational platform to explore Indonesian batik motifs with story-based content, interactive quizzes, and a curated catalog with marketplace directions.',
    role: 'Front-end Developer',
    tags: ['React', 'InertiaJS', 'Laravel', 'Tailwind', 'Framer Motion'],
    highlights: [
      'Built an educational platform to explore Indonesian batik motifs through catalog, stories, and interactive quizzes.',
      'Developed gamified quiz module to boost engagement and learning retention.',
      'Delivered admin dashboard for managing batik content and quiz questions.',
      'Admin dashboard for managing batik/quizzes content',
      'Marketplace direction for finding batik products (external purchase flow)',
    ],
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik1.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik2.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik3.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik4.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik5.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik6.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik7.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenalbatik8.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenalbatik9.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenalbatik10.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenalbatik11.png` },
    ],
    image: `${import.meta.env.BASE_URL}projects/kenalbatik.png`,
    links: { github: 'https://github.com/bektiyuda/KenalBatik' },
  },
  {
    id: 'ticketbuzz',
    title: 'TicketBuzz — Concert Ticketing Platform',
    description: 'A web-based concert ticketing platform focused on simplicity, featuring real-time payments via Midtrans and organizer tools for managing events and sales.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'Midtrans', 'Rest API'],
    highlights: [
      'Built a concert ticketing web app with streamlined booking flow and event catalog.',
      'Integrated payment gateway using Midtrans with payment status handling from API response.',
      'Developed purchase history for completed transactions.',
    ],
    image: `${import.meta.env.BASE_URL}projects/ticketbuzz.png`,
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz1.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz4.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz2.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz3.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz5.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz6.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz7.png` },
    ],
    links: {
      github: 'https://github.com/wildanzhafiri/TicketBuzz',
    },
  },
  {
    id: 'lentara',
    title: 'Lentara — Rental Marketplace Platform',
    description: 'A web-based rental marketplace built to make item renting more accessible and organized, helping users find what they need while enabling providers to manage their rental listings and transactions efficiently.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'Rest API', 'Midtrans'],
    highlights: [
      'User registration flow (sign up / sign in entry point)',
      'Homepage with category filter',
      'Product filtering (category, rating, price)',
      'Product detail page (rental duration, quantity, add to cart)',
      'Checkout experience with cost summary + voucher selection',
      'Provider dashboard with key stats and product management entry',
    ],
    image: `${import.meta.env.BASE_URL}projects/lentara.png`,
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara1.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara2.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara3.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara4.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara5.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara6.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara7.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara8.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara9.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara10.png` },
    ],
    links: {
      live: 'https://fe-intern-bcc.vercel.app/',
      github: 'https://github.com/wildanzhafiri/fe-intern-bcc',
    },
  },
  {
    id: 'domma',
    title: 'DOMMA — UMKM Cashier & Inventory Management',
    description: 'A web-based management system built to help UMKM run daily operations more efficiently by centralizing business processes into a single application.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'InertiaJS', 'Laravel'],
    highlights: [
      'Product management with full CRUD operations for inventory items',
      'Fast cashier workflow with auto-recorded transactions',
      'Real-time inventory updates synced to sales activity',
      'Dashboard summary (profit, daily sales, low-stock alerts) + automated reports',
      'Automatic receipt generation for completed transactions',
      'Role-based access control with different privileges for owners and employees',
    ],
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/domma/domma1.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma2.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma3.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma4.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma5.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma6.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma9.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma10.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma11.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma12.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma13.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma7.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma8.png` },
    ],
    image: `${import.meta.env.BASE_URL}projects/domma.png`,
    links: {
      // live: 'https://...',
      github: 'https://github.com/AiFahri/domma',
    },
  },
] as const;
