import type { Project } from './projects.types';

export const PROJECTS: readonly Project[] = [
  {
    id: 'bulkyhub',
    title: 'BulkyHub — Bulky Waste Pickup Platform',
    description: 'A scheduling and tracking platform for bulky waste pickup: residents submit requests, pick slots by RW capacity, and track status using a booking code.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'Framer Motion', 'Rest API'],
    highlights: [
      'Multi-step pickup request (user & location → items → verification summary)',
      'Slot-based scheduling per RW capacity + admin slot management',
      'Tracking page using booking code with status progression',
      'Field officer reporting with photo evidence upload',
    ],
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-landingpage.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-form.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-formdetail.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-verif.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-uploadproof.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-track.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-loginadmin.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-dashboard.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-pickuprequest.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-schedule.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-assignment.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-detailassignment.png` },
      { src: `${import.meta.env.BASE_URL}projects/bulkyhub/bulkyhub-truckmanagement.png` },
    ],

    image: `${import.meta.env.BASE_URL}projects/bulkyhub.png`,
    links: {
      github: 'https://github.com/wildanzhafiri/BulkyHub-FE',
    },
  },
  {
    id: 'laporin',
    title: 'LaporIn — Public Complaint Reporting System',
    description: 'A smart-city reporting web app where citizens submit complaints with a ticket number and track status, while admins verify and resolve reports.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'Rest API'],
    highlights: [
      'Complaint form with required fields + photo upload',
      'Ticket confirmation page + report history (list & detail)',
      'Status tracking: New / In Review / Rejected / Resolved',
      'Admin dashboard to review reports and update status with confirmation',
    ],
    image: `${import.meta.env.BASE_URL}projects/laporin.png`,
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin1.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin2.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin3.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin4.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin5.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin6.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin7.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin8.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin9.png` },
      { src: `${import.meta.env.BASE_URL}projects/laporin/laporin10.png` },
    ],
    links: {
      live: 'http://laporin.bccdev.id/admin',
      github: 'https://github.com/wildanzhafiri/fe-LaporIn',
    },
  },
  {
    id: 'kenalbatik',
    title: 'Kenal Batik — Cultural Education & Interactive Learning',
    description: 'An educational platform to explore Indonesian batik motifs with story-based content, interactive quizzes, and a curated catalog with marketplace directions.',
    role: 'Front-end Developer',
    tags: ['React', 'InertiaJS', 'Laravel', 'Tailwind', 'Framer Motion'],
    highlights: [
      'Batik catalog with region-based exploration + detailed overview per motif',
      'Interactive quiz module to increase engagement (gamified learning)',
      'Authentication (login/register) and profile experience',
      'Admin dashboard for managing batik/quizzes content',
      'Marketplace direction for finding batik products (external purchase flow)',
    ],
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik1.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik2.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik3.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik4.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik5.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik6.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenakbatik7.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenalbatik8.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenalbatik9.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenalbatik10.png` },
      { src: `${import.meta.env.BASE_URL}projects/kenalbatik/kenalbatik11.png` },
    ],
    image: `${import.meta.env.BASE_URL}projects/kenalbatik.png`,
    links: { github: 'https://github.com/bektiyuda/KenalBatik' },
  },
  {
    id: 'ticketbuzz',
    title: 'TicketBuzz — Concert Ticketing Platform',
    description: 'A web-based concert ticketing platform focused on simplicity, featuring real-time payments via Midtrans and organizer tools for managing events and sales.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'Midtrans', 'Rest API'],
    highlights: [
      'Concert catalog with search/filter and detailed event pages',
      'Simple booking flow with minimal steps and form validation',
      'Integrated payments via Midtrans (bank transfer, e-wallet, QRIS) with real-time confirmation',
      'E-ticket management with purchase history',
      'Organizer dashboard for event/ticket category management + sales analytics',
    ],
    image: `${import.meta.env.BASE_URL}projects/ticketbuzz.png`,
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz1.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz4.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz2.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz3.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz5.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz6.png` },
      { src: `${import.meta.env.BASE_URL}projects/ticketbuzz/ticketbuzz7.png` },
    ],
    links: {
      github: 'https://github.com/wildanzhafiri/TicketBuzz',
    },
  },
  {
    id: 'lentara',
    title: 'Lentara — Rental Marketplace Platform',
    description: 'A web-based rental marketplace built to make item renting more accessible and organized, helping users find what they need while enabling providers to manage their rental listings and transactions efficiently.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'Rest API', 'Midtrans'],
    highlights: [
      'User registration flow (sign up / sign in entry point)',
      'Homepage with category filter',
      'Product filtering (category, rating, price)',
      'Product detail page (rental duration, quantity, add to cart)',
      'Checkout experience with cost summary + voucher selection',
      'Provider dashboard with key stats and product management entry',
    ],
    image: `${import.meta.env.BASE_URL}projects/lentara.png`,
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara1.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara2.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara3.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara4.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara5.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara6.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara7.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara8.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara9.png` },
      { src: `${import.meta.env.BASE_URL}projects/lentara/lentara10.png` },
    ],
    links: {
      live: 'https://fe-intern-bcc.vercel.app/',
      github: 'https://github.com/wildanzhafiri/fe-intern-bcc',
    },
  },
  {
    id: 'domma',
    title: 'DOMMA — UMKM Cashier & Inventory Management',
    description: 'A web-based management system built to help UMKM run daily operations more efficiently by centralizing business processes into a single application.',
    role: 'Front-end Developer',
    tags: ['React', 'TypeScript', 'Tailwind', 'InertiaJS', 'Laravel'],
    highlights: [
      'Product management with full CRUD operations for inventory items',
      'Fast cashier workflow with auto-recorded transactions',
      'Real-time inventory updates synced to sales activity',
      'Dashboard summary (profit, daily sales, low-stock alerts) + automated reports',
      'Automatic receipt generation for completed transactions',
      'Role-based access control with different privileges for owners and employees',
    ],
    gallery: [
      { src: `${import.meta.env.BASE_URL}projects/domma/domma1.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma2.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma3.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma4.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma5.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma6.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma9.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma10.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma11.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma12.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma13.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma7.png` },
      { src: `${import.meta.env.BASE_URL}projects/domma/domma8.png` },
    ],
    image: `${import.meta.env.BASE_URL}projects/domma.png`,
    links: {
      // live: 'https://...',
      github: 'https://github.com/AiFahri/domma',
    },
  },
] as const;
